name:                bot
version:             0.1.0.0
github:              "githubuser/bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson 
- bytestring
- containers
- deriving-aeson
- dhall
- directory
- exceptions
- extra
- http-client-tls
- http-client
- conduit
- scientific
- http-types
- http-conduit
- mtl
- text
- time
- unordered-containers
- lens
- optparse-applicative
- QuickCheck
- generic-arbitrary
- hspec

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFunctor 
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- EmptyDataDeriving
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- ImplicitParams
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- UndecidableInstances
- UndecidableSuperClasses

library:
  source-dirs: src

executables:
  bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - bot

tests:
  bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
